org: enzogomez
service: microservice1

provider:
  name: aws
  runtime: python3.12
  iam:
    role: arn:aws:iam::353553552499:role/LabRole
  

resources:
  Resources:
    EstudiantesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Estudiantes
        AttributeDefinitions:
          - AttributeName: Universidad
            AttributeType: S
          - AttributeName: DNI
            AttributeType: S
          - AttributeName: Promedio
            AttributeType: N
          - AttributeName: Carrera
            AttributeType: S
          - AttributeName: Ciudad
            AttributeType: S
          - AttributeName: Fecha_Nacimiento
            AttributeType: S
          - AttributeName: ID_Estudiante
            AttributeType: S
        KeySchema:
          - AttributeName: Universidad
            KeyType: HASH
          - AttributeName: DNI
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST  # Modo de facturación "on-demand"
        
        # Definición del Índice Local Secundario (LSI) para Promedio
        LocalSecondaryIndexes:
          - IndexName: LSI_Promedio
            KeySchema:
              - AttributeName: Universidad
                KeyType: HASH
              - AttributeName: Promedio
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        
        # Definición de Índices Globales Secundarios (GSI)
        GlobalSecondaryIndexes:
          - IndexName: GSI_Carrera_Promedio
            KeySchema:
              - AttributeName: Carrera
                KeyType: HASH
              - AttributeName: Promedio
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            
          - IndexName: GSI_FechaNacimiento_IDEstudiante
            KeySchema:
              - AttributeName: Fecha_Nacimiento
                KeyType: HASH
              - AttributeName: ID_Estudiante
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
