service: estudiante-service

provider:
  name: aws
  runtime: python3.9  # Define el runtime de Python 3.9 para la Lambda
  region: us-east-1
  iam:
    role: arn:aws:iam::353553552499:role/LabRole  # ARN del rol IAM que especificaste

functions:
  buscarEstudiante:
    handler: handler.lambda_handler  # Define el archivo y la función manejadora (handler.py en este ejemplo)
    environment:
      DYNAMODB_TABLE: Estudiante  # Nombre de la tabla DynamoDB en variable de entorno
    events:
      - http:
          path: estudiantes/buscar
          method: get
          request:
            parameters:
              querystrings:
                ID-Estudiante: false
                Email: false

resources:
  Resources:
    EstudianteTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Estudiante
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: ID-Estudiante
            AttributeType: S
          - AttributeName: DNI
            AttributeType: S
          - AttributeName: Email
            AttributeType: S
          - AttributeName: Nro_Tel
            AttributeType: S
        KeySchema:
          - AttributeName: ID-Estudiante
            KeyType: HASH
          - AttributeName: DNI
            KeyType: RANGE
        LocalSecondaryIndexes:
          - IndexName: EmailIndex
            KeySchema:
              - AttributeName: ID-Estudiante
                KeyType: HASH
              - AttributeName: Email
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: NroTelIndex
            KeySchema:
              - AttributeName: ID-Estudiante
                KeyType: HASH
              - AttributeName: Nro_Tel
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        GlobalSecondaryIndexes:
          - IndexName: EmailGSI
            KeySchema:
              - AttributeName: Email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: DNIGSI
            KeySchema:
              - AttributeName: DNI
                KeyType: HASH
            Projection:
              ProjectionType: ALL
